site_name: Epip Encounters
site_url: https://pinewood.team/epip/
theme: readthedocs
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - toc:
        permalink: True
    # - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    # - pymdownx.superfences
    - attr_list
    - md_in_html

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Patch Notes: patchnotes.md
  - Beta Versions: beta.md
  - FAQ: Info/faq.md
  - Features:
    - "UI improvements": "Features/UI.md"
    - "Vanity": "Features/Vanity.md"
  - Documentation: 
    - "Introduction": "docs.md"
    - "Client":
      - "Pointer": "Documentation/Client/Pointer.md"
      - Generic UI:
        - Introduction: "Documentation/Client/UI/Generic/Introduction.md"
        - Elements:
          - Element: "Documentation/Client/UI/Generic/Elements/Element.md"
          - Button: "Documentation/Client/UI/Generic/Elements/Button.md"
          - Color: "Documentation/Client/UI/Generic/Elements/Color.md"
          - ComboBox: "Documentation/Client/UI/Generic/Elements/ComboBox.md"
    - "Utilities":
      - "Artifact": "Documentation/Utilities/Artifact.md"
      - "Character": "Documentation/Utilities/Character.md"
      - "Color": "Documentation/Utilities/Color.md"
      - "Combat": "Documentation/Utilities/Combat.md"
      - "GameState": "Documentation/Utilities/GameState.md"
      - "Item": "Documentation/Utilities/Item.md"
      - "Mod": "Documentation/Utilities/Mod.md"
      - "Net": "Documentation/Utilities/Net.md"
      - "Timer": "Documentation/Utilities/Timer.md"
      - "Text": "Documentation/Utilities/Text.md"
      - "Vector": "Documentation/Utilities/Vector.md"
  #   - "Global Tables":
  #     - "Feature": "Global Tables/Feature.md"
  #   - "Game":
  #     - "Root": "Game/index.md"
  #     - "Character": "Game/Character.md"
  #     - "Item": "Game/Item.md"
  #   - "Client":
  #     - "Root": "Client/index.md"
  #     # - "Input": "Client/input.md"
  #     - "UI":
  #       - "ChatLog" : "Client/UI/ChatLog.md"
  #       - "OptionsSettings" : "Client/UI/OptionsSettings.md"
  #       - "OptionsInput" : "Client/UI/OptionsInput.md"
  #       - "Examine": "Client/UI/Examine.md"
  #       - "MessageBox": "Client/UI/MessageBox.md"
  #       - "CharacterSheet": "Client/UI/CharacterSheet.md"
  #       - "GiftBagContent": "Client/UI/GiftBagContent.md"
  #   - "Epip":
  #     - "Root": "Epip/index.md"
  #     - "Features":
  #       - "EpicEnemies" : "Epip/EpicEnemies.md"
  #       - "StatsTab": "Epip/StatsTab.md"
  - Tutorials:
    # - "Lua": "Tutorials/Lua/index.md"
    - "Testing": "Tutorials/testing.md"
  - Maintenance:
    - "Index": "Maintenance/index.md"
    - "Localization": "Maintenance/localization.md"
    - "Documentation": "Maintenance/documentation.md"