site_name: Epip Encounters
site_url: https://pinewood.team/epip/
theme:
  name: material
  collapse_navigation: false
  navigation_depth: 3
  logo: img/tpw_logo_purple.png
  favicon: img/tpw_logo_purple.png
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - toc:
        permalink: True
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.keys:
        key_map: {
          "m1": "Left Mouse Button",
          "m2": "Right Mouse Button",
          "m3": "Middle Mouse Button",
          "m4": "Mouse M4",
          "m5": "Mouse M5",
        }
    - admonition
    - attr_list
    - md_in_html
extra:
  analytics:
    provider: google
    property: G-K2XG4QX6F3
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
plugins:
  - search
  - meta-descriptions
  - mkdocs-video:
      css_style:
        height: "400px"
        width: "100%"

nav:
  - Home: index.md
  - Patch Notes: patchnotes.md
  - Beta Versions: beta.md
  - FAQ: Info/faq.md
  - Major Features:
    - "UI Improvements": "Features/UI.md"
    - "Vanity": "Features/Vanity.md"
    - "Quick Find": "Features/QuickFind.md"
    - "Animation Cancelling": "Features/AnimationCancelling.md"
    - "Hotbar Groups": "Features/HotbarGroups.md"
    - "Camera": "Features/Camera.md"
    - "Tooltip Adjustments": "Features/TooltipAdjustments.md"
    - "Vanilla Fixes": "Features/VanillaFixes.md"
  - Technical Documentation: 
    - "Introduction": "docs.md"
    - "Terminology": "Documentation/Terminology.md"
    - "Important Tables": "Documentation/Global Tables/Epip.md"
    - Client:
      - "Pointer": "Documentation/Client/Pointer.md"
    - Generic UI:
      - Introduction: "Documentation/Client/UI/Generic/Introduction.md"
      - Element: "Documentation/Client/UI/Generic/Elements/Element.md"
      - Button: "Documentation/Client/UI/Generic/Elements/Button.md"
      - Color: "Documentation/Client/UI/Generic/Elements/Color.md"
      - ComboBox: "Documentation/Client/UI/Generic/Elements/ComboBox.md"
    - Generic Prefabs:
      - Button: "Documentation/Client/UI/Generic/Prefabs/Button.md"
    - Utilities:
      - "Artifact": "Documentation/Utilities/Artifact.md"
      - "Character": "Documentation/Utilities/Character.md"
      - "Color": "Documentation/Utilities/Color.md"
      - "Combat": "Documentation/Utilities/Combat.md"
      - "GameState": "Documentation/Utilities/GameState.md"
      - "Item": "Documentation/Utilities/Item.md"
      - "Mod": "Documentation/Utilities/Mod.md"
      - "Net": "Documentation/Utilities/Net.md"
      - "Timer": "Documentation/Utilities/Timer.md"
      - "Text": "Documentation/Utilities/Text.md"
      - "Vector": "Documentation/Utilities/Vector.md"
      - "OOP": "Documentation/Utilities/OOP.md"
      - "Library": "Documentation/Utilities/Library.md"
      - "IO": "Documentation/Utilities/IO.md"
      - "Coroutine": "Documentation/Utilities/Coroutine.md"
      - "UserVars": "Documentation/Utilities/UserVars.md"
      - "Texture": "Documentation/Utilities/Texture.md"
      - "Pointer": "Documentation/Utilities/Pointer.md"
  #   - "Global Tables":
  #     - "Feature": "Global Tables/Feature.md"
  #   - "Game":
  #     - "Root": "Game/index.md"
  #     - "Character": "Game/Character.md"
  #     - "Item": "Game/Item.md"
  #   - "Client":
  #     - "Root": "Client/index.md"
  #     # - "Input": "Client/input.md"
  #     - "UI":
  #       - "ChatLog" : "Client/UI/ChatLog.md"
  #       - "OptionsSettings" : "Client/UI/OptionsSettings.md"
  #       - "OptionsInput" : "Client/UI/OptionsInput.md"
  #       - "Examine": "Client/UI/Examine.md"
  #       - "MessageBox": "Client/UI/MessageBox.md"
  #       - "CharacterSheet": "Client/UI/CharacterSheet.md"
  #       - "GiftBagContent": "Client/UI/GiftBagContent.md"
  #   - "Epip":
  #     - "Root": "Epip/index.md"
  #     - "Features":
  #       - "EpicEnemies" : "Epip/EpicEnemies.md"
  #       - "StatsTab": "Epip/StatsTab.md"
  - Development:
    - Tutorials:
      # - "Lua": "Tutorials/Lua/index.md"
      - "Testing": "Tutorials/testing.md"
    - Maintenance:
      - "Index": "Maintenance/index.md"
      - "Project Setup": Maintenance/ProjectSetup.md
      - "IDE Setup": "Maintenance/IDESetup.md"
      - "Localization": "Maintenance/localization.md"
      - "Documentation": "Maintenance/documentation.md"
      - "Keybinds Reference": "Maintenance/keybinds.md"